// Generated by https://quicktype.io

export interface Settings {
  global: Global;
  gmailSettings: GmailSettings;
  misc: Misc;
}

export interface Global {
  webhook: string;
  activated: boolean;
  key: string;
  chromePath: string;
}

export interface GmailSettings {
  maxRunning: number;
  sleepinputlow: number;
  sleepinputhigh: number;
  runinputlow: number;
  runinputhigh: number;
}

export interface Misc {
  gmailToken: string;
  fivesim: string;
  twoCaptcha: string;
  authorizedToken: string;
  botToken: string;
}
