import {
  loadProfiles,
  deleteGroup,
  deleteProfile,
  addProfile,
  importProfiles,
  saveProfiles,
  exportProfiles,
  newGroup,
  deleteSelected,
  copyProfiles,
  getGroups,
  moveProfiles,
  deleteAll,
  getProfile,
  jigProfiles,
  editGroup,
} from "./converter/converter_main";

export default {
  loadProfiles,
  getProfile,
  deleteProfile,
  addProfile,
  importProfiles,
  saveProfiles,
  exportProfiles,
  newGroup,
  deleteSelected,
  copyProfiles,
  getGroups,
  moveProfiles,
  deleteAll,
  deleteGroup,
  editGroup,
  jigProfiles,
};
